// ===================================
// Data Models & State Management
// ===================================
class AppState {
  constructor() {
    this.carriers = this.loadFromStorage('carriers') || [];
    this.progress = this.loadFromStorage('progress') || [];
    this.orders = this.loadFromStorage('orders') || [];
    this.currentView = 'dashboard';
    this.nextSequence = this.loadFromStorage('nextSequence') || 1;
  }
  loadFromStorage(key) {
    try {
      const data = localStorage.getItem(key);
      return data ? JSON.parse(data) : null;
    } catch (e) {
      console.error(`Error loading ${key}:`, e);
      return null;
    }
  }
  saveToStorage(key, data) {
    try {
      localStorage.setItem(key, JSON.stringify(data));
    } catch (e) {
      console.error(`Error saving ${key}:`, e);
    }
  }
  // Carrier Master CRUD
  addCarrier(carrier) {
    this.carriers.push(carrier);
    this.saveToStorage('carriers', this.carriers);
  }
  updateCarrier(tadig, updatedCarrier) {
    const index = this.carriers.findIndex(c => c.tadig === tadig);
    if (index !== -1) {
      this.carriers[index] = updatedCarrier;
      this.saveToStorage('carriers', this.carriers);
    }
  }
  deleteCarrier(tadig) {
    this.carriers = this.carriers.filter(c => c.tadig !== tadig);
    this.saveToStorage('carriers', this.carriers);
  }
  getCarrier(tadig) {
    return this.carriers.find(c => c.tadig === tadig);
  }
  // Progress Management CRUD
  addProgress(progress) {
    progress.sequence = this.nextSequence++;
    progress.createdAt = new Date().toISOString();
    this.progress.push(progress);
    this.saveToStorage('progress', this.progress);
    this.saveToStorage('nextSequence', this.nextSequence);
    
    // Auto-create order if gate conditions are met
    this.checkAndCreateOrder(progress);
  }
  updateProgress(sequence, updatedProgress) {
    const index = this.progress.findIndex(p => p.sequence === sequence);
    if (index !== -1) {
      const oldProgress = this.progress[index];
      this.progress[index] = { ...updatedProgress, sequence };
      this.saveToStorage('progress', this.progress);
      
      // Check if order needs to be created/updated
      this.checkAndCreateOrder(this.progress[index], oldProgress);
    }
  }
  deleteProgress(sequence) {
    this.progress = this.progress.filter(p => p.sequence !== sequence);
    this.saveToStorage('progress', this.progress);
    
    // Also delete related order
    const progressItem = this.progress.find(p => p.sequence === sequence);
    if (progressItem) {
      this.deleteOrder(progressItem.tadig);
    }
  }
  getProgress(sequence) {
    return this.progress.find(p => p.sequence === sequence);
  }
  // Order Dependency CRUD
  addOrder(order) {
    this.orders.push(order);
    this.saveToStorage('orders', this.orders);
  }
  updateOrder(tadig, updatedOrder) {
    const index = this.orders.findIndex(o => o.tadig === tadig);
    if (index !== -1) {
      this.orders[index] = updatedOrder;
      this.saveToStorage('orders', this.orders);
    } else {
      this.addOrder(updatedOrder);
    }
  }
  deleteOrder(tadig) {
    this.orders = this.orders.filter(o => o.tadig !== tadig);
    this.saveToStorage('orders', this.orders);
  }
  getOrder(tadig) {
    return this.orders.find(o => o.tadig === tadig);
  }
  // Auto-create order based on gate conditions
  checkAndCreateOrder(progress, oldProgress = null) {
    // Check if any gate condition is filled
    const hasGateCondition = progress.qaDate || progress.simDate || 
                            progress.ir2Date || progress.testSheetDate;
    
    if (hasGateCondition) {
      const carrier = this.getCarrier(progress.tadig);
      const existingOrder = this.getOrder(progress.tadig);
      
      const order = {
        tadig: progress.tadig,
        carrierName: carrier ? carrier.name : '',
        dnsDate: existingOrder?.dnsDate || '',
        mmeDate: existingOrder?.mmeDate || '',
        tccDate: existingOrder?.tccDate || '',
        verificationDate: existingOrder?.verificationDate || '',
        configLimit: existingOrder?.configLimit || '',
        priority: progress.priority || '中',
        autoGenerated: true,
        sourceSequence: progress.sequence
      };
      
      this.updateOrder(progress.tadig, order);
    }
  }
  // Statistics
  getStats() {
    return {
      totalCarriers: this.carriers.length,
      activeProjects: this.progress.filter(p => !this.isProjectComplete(p)).length,
      completedProjects: this.progress.filter(p => this.isProjectComplete(p)).length,
      pendingOrders: this.orders.filter(o => !o.verificationDate).length
    };
  }
  isProjectComplete(progress) {
    return progress.qaDate && progress.simDate && 
           progress.ir2Date && progress.testSheetDate &&
           progress.tdTapDate && progress.syniverseDate;
  }
  getProjectStatus(progress) {
    const gates = [
      progress.qaDate,
      progress.simDate,
      progress.ir2Date,
      progress.testSheetDate,
      progress.tdTapDate,
      progress.syniverseDate
    ];
    
    const completedGates = gates.filter(g => g).length;
    
    if (completedGates === 0) return 'new';
    if (completedGates === gates.length) return 'complete';
    return 'progress';
  }
}
// Global state
const state = new AppState();
// ===================================
// View Management
// ===================================
function switchView(viewName) {
  // Hide all views
  document.querySelectorAll('.view-container').forEach(view => {
    view.classList.add('hidden');
  });
  
  // Show selected view
  const viewMap = {
    'dashboard': 'dashboardView',
    'master': 'masterView',
    'progress': 'progressView',
    'order': 'orderView'
  };
  
  const viewId = viewMap[viewName];
  if (viewId) {
    document.getElementById(viewId).classList.remove('hidden');
  }
  
  // Update navigation
  document.querySelectorAll('.sidebar-nav-link').forEach(link => {
    link.classList.remove('active');
  });
  
  const activeLink = document.querySelector(`[data-view="${viewName}"]`);
  if (activeLink) {
    activeLink.classList.add('active');
  }
  
  state.currentView = viewName;
  
  // Render the view
  renderView(viewName);
}
function renderView(viewName) {
  switch(viewName) {
    case 'dashboard':
      renderDashboard();
      break;
    case 'master':
      renderMasterTable();
      break;
    case 'progress':
      renderProgressTable();
      break;
    case 'order':
      renderOrderTable();
      break;
  }
}
// ===================================
// Dashboard Rendering
// ===================================
function renderDashboard() {
  const stats = state.getStats();
  
  document.getElementById('statTotalCarriers').textContent = stats.totalCarriers;
  document.getElementById('statActiveProjects').textContent = stats.activeProjects;
  document.getElementById('statCompletedProjects').textContent = stats.completedProjects;
  document.getElementById('statPendingOrders').textContent = stats.pendingOrders;
  
  // Render charts
  renderProgressChart();
  renderStatusChart();
  renderManagerChart();
  renderPriorityChart();
  renderGateAchievement();
  
  // Render recent activity
  const recentActivity = document.getElementById('recentActivity');
  
  if (state.progress.length === 0) {
    recentActivity.innerHTML = `
      <div class="empty-state">
        <div class="empty-state-icon">📝</div>
        <div class="empty-state-text">まだデータがありません</div>
        <button class="btn btn-primary mt-md" onclick="switchView('progress')">
          最初の案件を追加
        </button>
      </div>
    `;
  } else {
    const recent = [...state.progress]
      .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
      .slice(0, 5);
    
    recentActivity.innerHTML = `
      <div class="table-container">
        <table class="table">
          <thead>
            <tr>
              <th>シーケンス</th>
              <th>TADIG</th>
              <th>担当者</th>
              <th>ステータス</th>
              <th>優先順位</th>
            </tr>
          </thead>
          <tbody>
            ${recent.map(p => {
              const carrier = state.getCarrier(p.tadig);
              const status = state.getProjectStatus(p);
              return `
                <tr>
                  <td>${p.sequence}</td>
                  <td>${p.tadig} ${carrier ? [(${carrier.name})](cci:1://file:///Users/hashi/Desktop/hair%20salon%20HP/%E3%83%AD%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0%E6%A1%88%E4%BB%B6%E7%AE%A1%E7%90%86/app.js:361:12-367:13) : ''}</td>
                  <td>${p.manager}</td>
                  <td>${getStatusBadge(status)}</td>
                  <td>${getPriorityBadge(p.priority)}</td>
                </tr>
              `;
            }).join('')}
          </tbody>
        </table>
      </div>
    `;
  }
}
// ===================================
// Chart Rendering Functions
// ===================================
let charts = {};
function destroyChart(chartId) {
  if (charts[chartId]) {
    charts[chartId].destroy();
    delete charts[chartId];
  }
}
function renderProgressChart() {
  const ctx = document.getElementById('progressChart');
  if (!ctx) return;
  
  destroyChart('progressChart');
  
  const totalProjects = state.progress.length;
  const completedProjects = state.progress.filter(p => state.isProjectComplete(p)).length;
  const progressRate = totalProjects > 0 ? Math.round((completedProjects / totalProjects) * 100) : 0;
  
  charts.progressChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['完了', '未完了'],
      datasets: [{
        data: [completedProjects, totalProjects - completedProjects],
        backgroundColor: [
          'rgba(16, 185, 129, 0.8)',
          'rgba(209, 213, 219, 0.5)'
        ],
        borderColor: [
          'rgba(16, 185, 129, 1)',
          'rgba(209, 213, 219, 1)'
        ],
        borderWidth: 2
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: 'bottom',
          labels: {
            font: { size: 13, weight: '600' },
            padding: 15
          }
        },
        tooltip: {
          callbacks: {
            label: function(context) {
              const label = context.label || '';
              const value = context.parsed || 0;
              const total = context.dataset.data.reduce((a, b) => a + b, 0);
              const percentage = total > 0 ? Math.round((value / total) * 100) : 0;
              return `${label}: ${value}件 (${percentage}%)`;
            }
          }
        }
      }
    }
  });
}
function renderStatusChart() {
  const ctx = document.getElementById('statusChart');
  if (!ctx) return;
  
  destroyChart('statusChart');
  
  const statusCounts = {
    new: state.progress.filter(p => state.getProjectStatus(p) === 'new').length,
    progress: state.progress.filter(p => state.getProjectStatus(p) === 'progress').length,
    complete: state.progress.filter(p => state.getProjectStatus(p) === 'complete').length
  };
  
  charts.statusChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: ['新規', '進行中', '完了'],
      datasets: [{
        data: [statusCounts.new, statusCounts.progress, statusCounts.complete],
        backgroundColor: [
          'rgba(59, 130, 246, 0.8)',
          'rgba(245, 158, 11, 0.8)',
          'rgba(16, 185, 129, 0.8)'
        ],
        borderColor: [
          'rgba(59, 130, 246, 1)',
          'rgba(245, 158, 11, 1)',
          'rgba(16, 185, 129, 1)'
        ],
        borderWidth: 2
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: 'bottom',
          labels: {
            font: { size: 13, weight: '600' },
            padding: 15
          }
        },
        tooltip: {
          callbacks: {
            label: function(context) {
              const label = context.label || '';
              const value = context.parsed || 0;
              const total = context.dataset.data.reduce((a, b) => a + b, 0);
              const percentage = total > 0 ? Math.round((value / total) * 100) : 0;
              return `${label}: ${value}件 (${percentage}%)`;
            }
          }
        }
      }
    }
  });
}
function renderManagerChart() {
  const ctx = document.getElementById('managerChart');
  if (!ctx) return;
  
  destroyChart('managerChart');
  
  // Count projects by manager
  const managerCounts = {};
  state.progress.forEach(p => {
    managerCounts[p.manager] = (managerCounts[p.manager] || 0) + 1;
  });
  
  const managers = Object.keys(managerCounts).sort((a, b) => managerCounts[b] - managerCounts[a]);
  const counts = managers.map(m => managerCounts[m]);
  
  charts.managerChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: managers.length > 0 ? managers : ['データなし'],
      datasets: [{
        label: '案件数',
        data: counts.length > 0 ? counts : [0],
        backgroundColor: 'rgba(124, 58, 237, 0.8)',
        borderColor: 'rgba(124, 58, 237, 1)',
        borderWidth: 2,
        borderRadius: 8
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          beginAtZero: true,
          ticks: {
            stepSize: 1,
            font: { size: 12, weight: '600' }
          },
          grid: {
            color: 'rgba(0, 0, 0, 0.05)'
          }
        },
        x: {
          ticks: {
            font: { size: 12, weight: '600' }
          },
          grid: {
            display: false
          }
        }
      },
      plugins: {
        legend: {
          display: false
        },
        tooltip: {
          callbacks: {
            label: function(context) {
              return `案件数: ${context.parsed.y}件`;
            }
          }
        }
      }
    }
  });
}
function renderPriorityChart() {
  const ctx = document.getElementById('priorityChart');
  if (!ctx) return;
  
  destroyChart('priorityChart');
  
  const priorityCounts = {
    '高': state.progress.filter(p => p.priority === '高').length,
    '中': state.progress.filter(p => p.priority === '中').length,
    '低': state.progress.filter(p => p.priority === '低').length
  };
  
  charts.priorityChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['高', '中', '低'],
      datasets: [{
        data: [priorityCounts['高'], priorityCounts['中'], priorityCounts['低']],
        backgroundColor: [
          'rgba(239, 68, 68, 0.8)',
          'rgba(245, 158, 11, 0.8)',
          'rgba(107, 114, 128, 0.8)'
        ],
        borderColor: [
          'rgba(239, 68, 68, 1)',
          'rgba(245, 158, 11, 1)',
          'rgba(107, 114, 128, 1)'
        ],
        borderWidth: 2
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: 'bottom',
          labels: {
            font: { size: 13, weight: '600' },
            padding: 15
          }
        },
        tooltip: {
          callbacks: {
            label: function(context) {
              const label = context.label || '';
              const value = context.parsed || 0;
              const total = context.dataset.data.reduce((a, b) => a + b, 0);
              const percentage = total > 0 ? Math.round((value / total) * 100) : 0;
              return `優先度${label}: ${value}件 (${percentage}%)`;
            }
          }
        }
      }
    }
  });
}
function renderGateAchievement() {
  const container = document.getElementById('gateAchievement');
  if (!container) return;
  
  if (state.progress.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <div class="empty-state-icon">🎯</div>
        <div class="empty-state-text">まだデータがありません</div>
      </div>
    `;
    return;
  }
  
  const gates = [
    { key: 'qaDate', label: 'QA受領' },
    { key: 'simDate', label: 'SIM受領' },
    { key: 'ir2Date', label: 'IR2受領' },
    { key: 'testSheetDate', label: '試験シート受領' },
    { key: 'tdTapDate', label: 'TD TAP設定' },
    { key: 'syniverseDate', label: 'Syniverse設定' }
  ];
  
  const totalProjects = state.progress.length;
  
  container.innerHTML = `
    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px;">
      ${gates.map(gate => {
        const completed = state.progress.filter(p => p[gate.key]).length;
        const percentage = Math.round((completed / totalProjects) * 100);
        
        return `
          <div style="padding: 16px; background: rgba(255, 255, 255, 0.6); border-radius: 12px; border: 1px solid rgba(0, 0, 0, 0.05);">
            <div style="font-size: 13px; font-weight: 600; color: #6b7280; margin-bottom: 8px;">${gate.label}</div>
            <div style="font-size: 24px; font-weight: 700; background: linear-gradient(135deg, #2563eb, #7c3aed); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 8px;">
              ${completed}/${totalProjects}
            </div>
            <div style="width: 100%; height: 8px; background: rgba(0, 0, 0, 0.05); border-radius: 999px; overflow: hidden;">
              <div style="width: ${percentage}%; height: 100%; background: linear-gradient(90deg, #2563eb, #7c3aed); transition: width 0.3s ease;"></div>
            </div>
            <div style="font-size: 12px; color: #6b7280; margin-top: 4px; text-align: right;">${percentage}%</div>
          </div>
        `;
      }).join('')}
    </div>
  `;
}
// ===================================
// Master Table Rendering
// ===================================
function renderMasterTable(searchTerm = '') {
  const tbody = document.getElementById('masterTableBody');
  
  let carriers = state.carriers;
  
  // Filter by search term
  if (searchTerm) {
    const term = searchTerm.toLowerCase();
    carriers = carriers.filter(c => 
      c.tadig.toLowerCase().includes(term) ||
      c.name.toLowerCase().includes(term)
    );
  }
  
  if (carriers.length === 0) {
    tbody.innerHTML = `
      <tr>
        <td colspan="6">
          <div class="empty-state">
            <div class="empty-state-icon">📋</div>
            <div class="empty-state-text">
              ${searchTerm ? '検索結果がありません' : 'マスターデータがありません'}
            </div>
          </div>
        </td>
      </tr>
    `;
    return;
  }
  
  tbody.innerHTML = carriers.map(carrier => `
    <tr>
      <td><strong>${carrier.tadig}</strong></td>
      <td>${carrier.name}</td>
      <td>${carrier.country}</td>
      <td>${carrier.plmn}</td>
      <td>${carrier.serviceType}</td>
      <td>
        <div class="table-actions">
          <button class="btn btn-sm btn-secondary" onclick="editMaster('${carrier.tadig}')">
            ✏️ 編集
          </button>
          <button class="btn btn-sm btn-danger" onclick="deleteMasterConfirm('${carrier.tadig}')">
            🗑️ 削除
          </button>
        </div>
      </td>
    </tr>
  `).join('');
}
// ===================================
// Progress Table Rendering
// ===================================
function renderProgressTable(searchTerm = '') {
  const tbody = document.getElementById('progressTableBody');
  
  let progressList = state.progress;
  
  // Filter by search term
  if (searchTerm) {
    const term = searchTerm.toLowerCase();
    progressList = progressList.filter(p => {
      const carrier = state.getCarrier(p.tadig);
      return p.tadig.toLowerCase().includes(term) ||
             p.manager.toLowerCase().includes(term) ||
             (carrier && carrier.name.toLowerCase().includes(term));
    });
  }
  
  if (progressList.length === 0) {
    tbody.innerHTML = `
      <tr>
        <td colspan="9">
          <div class="empty-state">
            <div class="empty-state-icon">📈</div>
            <div class="empty-state-text">
              ${searchTerm ? '検索結果がありません' : '進捗案件がありません'}
            </div>
          </div>
        </td>
      </tr>
    `;
    return;
  }
  
  tbody.innerHTML = progressList.map(progress => {
    const carrier = state.getCarrier(progress.tadig);
    const status = state.getProjectStatus(progress);
    
    return `
      <tr>
        <td><strong>${progress.sequence}</strong></td>
        <td>${progress.tadig}</td>
        <td>${carrier ? carrier.name : '-'}</td>
        <td>${progress.manager}</td>
        <td>${progress.startDate || '-'}</td>
        <td>${progress.serviceMethod}</td>
        <td>${getPriorityBadge(progress.priority)}</td>
        <td>${getStatusBadge(status)}</td>
        <td>
          <div class="table-actions">
            <button class="btn btn-sm btn-secondary" onclick="editProgress(${progress.sequence})">
              ✏️ 編集
            </button>
            <button class="btn btn-sm btn-danger" onclick="deleteProgressConfirm(${progress.sequence})">
              🗑️ 削除
            </button>
          </div>
        </td>
      </tr>
    `;
  }).join('');
}
// ===================================
// Order Table Rendering
// ===================================
function renderOrderTable(searchTerm = '') {
  const tbody = document.getElementById('orderTableBody');
  
  let orders = state.orders;
  
  // Filter by search term
  if (searchTerm) {
    const term = searchTerm.toLowerCase();
    orders = orders.filter(o => 
      o.tadig.toLowerCase().includes(term) ||
      o.carrierName.toLowerCase().includes(term)
    );
  }
  
  if (orders.length === 0) {
    tbody.innerHTML = `
      <tr>
        <td colspan="9">
          <div class="empty-state">
            <div class="empty-state-icon">⚙️</div>
            <div class="empty-state-text">
              ${searchTerm ? '検索結果がありません' : 'オーダーがありません'}
            </div>
            <div class="empty-state-text" style="font-size: 13px; margin-top: 8px;">
              進捗管理表でGate条件を入力すると自動的に作成されます
            </div>
          </div>
        </td>
      </tr>
    `;
    return;
  }
  
  tbody.innerHTML = orders.map(order => `
    <tr>
      <td><strong>${order.tadig}</strong></td>
      <td>${order.carrierName}</td>
      <td>${order.dnsDate || '-'}</td>
      <td>${order.mmeDate || '-'}</td>
      <td>${order.tccDate || '-'}</td>
      <td>${order.verificationDate || '-'}</td>
      <td>${order.configLimit || '-'}</td>
      <td>${getPriorityBadge(order.priority)}</td>
      <td>
        <div class="table-actions">
          <button class="btn btn-sm btn-secondary" onclick="editOrder('${order.tadig}')">
            ✏️ 編集
          </button>
        </div>
      </td>
    </tr>
  `).join('');
}
// ===================================
// Helper Functions
// ===================================
function getStatusBadge(status) {
  const badges = {
    'new': '<span class="badge badge-new">新規</span>',
    'progress': '<span class="badge badge-progress">進行中</span>',
    'complete': '<span class="badge badge-complete">完了</span>'
  };
  return badges[status] || badges['new'];
}
function getPriorityBadge(priority) {
  const badges = {
    '高': '<span class="badge badge-urgent">高</span>',
    '中': '<span class="badge badge-progress">中</span>',
    '低': '<span class="badge badge-pending">低</span>'
  };
  return badges[priority] || badges['中'];
}
// ===================================
// Master Modal Functions
// ===================================
function openMasterModal() {
  document.getElementById('masterModalTitle').textContent = 'マスター追加';
  document.getElementById('masterForm').reset();
  document.getElementById('masterEditId').value = '';
  document.getElementById('masterModal').classList.remove('hidden');
}
function closeMasterModal() {
  document.getElementById('masterModal').classList.add('hidden');
}
function editMaster(tadig) {
  const carrier = state.getCarrier(tadig);
  if (!carrier) return;
  
  document.getElementById('masterModalTitle').textContent = 'マスター編集';
  document.getElementById('masterEditId').value = tadig;
  document.getElementById('masterTadig').value = carrier.tadig;
  document.getElementById('masterName').value = carrier.name;
  document.getElementById('masterCountry').value = carrier.country;
  document.getElementById('masterPlmn').value = carrier.plmn;
  document.getElementById('masterServiceType').value = carrier.serviceType;
  
  // Disable TADIG field when editing
  document.getElementById('masterTadig').readOnly = true;
  
  document.getElementById('masterModal').classList.remove('hidden');
}
function saveMaster() {
  const form = document.getElementById('masterForm');
  if (!form.checkValidity()) {
    form.reportValidity();
    return;
  }
  
  const editId = document.getElementById('masterEditId').value;
  const carrier = {
    tadig: document.getElementById('masterTadig').value.trim(),
    name: document.getElementById('masterName').value.trim(),
    country: document.getElementById('masterCountry').value.trim(),
    plmn: document.getElementById('masterPlmn').value.trim(),
    serviceType: document.getElementById('masterServiceType').value
  };
  
  if (editId) {
    state.updateCarrier(editId, carrier);
  } else {
    // Check for duplicate TADIG
    if (state.getCarrier(carrier.tadig)) {
      alert('このTADIGは既に登録されています');
      return;
    }
    state.addCarrier(carrier);
  }
  
  closeMasterModal();
  renderMasterTable();
  renderDashboard();
  
  // Re-enable TADIG field
  document.getElementById('masterTadig').readOnly = false;
}
function deleteMasterConfirm(tadig) {
  const carrier = state.getCarrier(tadig);
  if (!carrier) return;
  
  // Check if carrier is used in progress
  const inUse = state.progress.some(p => p.tadig === tadig);
  if (inUse) {
    alert('このキャリアは進捗管理表で使用されているため削除できません');
    return;
  }
  
  if (confirm(`${carrier.name} (${tadig}) を削除しますか?`)) {
    state.deleteCarrier(tadig);
    renderMasterTable();
    renderDashboard();
  }
}
// ===================================
// Progress Modal Functions
// ===================================
function openProgressModal() {
  document.getElementById('progressModalTitle').textContent = '進捗案件追加';
  document.getElementById('progressForm').reset();
  document.getElementById('progressEditId').value = '';
  
  // Populate TADIG dropdown
  populateTadigDropdown();
  
  document.getElementById('progressModal').classList.remove('hidden');
}
function closeProgressModal() {
  document.getElementById('progressModal').classList.add('hidden');
}
function populateTadigDropdown() {
  const select = document.getElementById('progressTadig');
  select.innerHTML = '<option value="">選択してください</option>';
  
  state.carriers.forEach(carrier => {
    const option = document.createElement('option');
    option.value = carrier.tadig;
    option.textContent = `${carrier.tadig} - ${carrier.name}`;
    select.appendChild(option);
  });
}
function editProgress(sequence) {
  const progress = state.getProgress(sequence);
  if (!progress) return;
  
  document.getElementById('progressModalTitle').textContent = '進捗案件編集';
  document.getElementById('progressEditId').value = sequence;
  
  populateTadigDropdown();
  
  document.getElementById('progressTadig').value = progress.tadig;
  document.getElementById('progressManager').value = progress.manager;
  document.getElementById('progressStartDate').value = progress.startDate || '';
  document.getElementById('progressServiceMethod').value = progress.serviceMethod;
  document.getElementById('progressRevenue').value = progress.revenue || '';
  document.getElementById('progressPriority').value = progress.priority;
  document.getElementById('progressQaDate').value = progress.qaDate || '';
  document.getElementById('progressSimDate').value = progress.simDate || '';
  document.getElementById('progressIr2Date').value = progress.ir2Date || '';
  document.getElementById('progressTestSheetDate').value = progress.testSheetDate || '';
  document.getElementById('progressTdTapDate').value = progress.tdTapDate || '';
  document.getElementById('progressSyniverseDate').value = progress.syniverseDate || '';
  
  document.getElementById('progressModal').classList.remove('hidden');
}
function saveProgress() {
  const form = document.getElementById('progressForm');
  if (!form.checkValidity()) {
    form.reportValidity();
    return;
  }
  
  const editId = document.getElementById('progressEditId').value;
  const progress = {
    tadig: document.getElementById('progressTadig').value,
    manager: document.getElementById('progressManager').value.trim(),
    startDate: document.getElementById('progressStartDate').value,
    serviceMethod: document.getElementById('progressServiceMethod').value,
    revenue: parseFloat(document.getElementById('progressRevenue').value) || null,
    priority: document.getElementById('progressPriority').value,
    qaDate: document.getElementById('progressQaDate').value,
    simDate: document.getElementById('progressSimDate').value,
    ir2Date: document.getElementById('progressIr2Date').value,
    testSheetDate: document.getElementById('progressTestSheetDate').value,
    tdTapDate: document.getElementById('progressTdTapDate').value,
    syniverseDate: document.getElementById('progressSyniverseDate').value
  };
  
  if (editId) {
    state.updateProgress(parseInt(editId), progress);
  } else {
    state.addProgress(progress);
  }
  
  closeProgressModal();
  renderProgressTable();
  renderOrderTable();
  renderDashboard();
}
function deleteProgressConfirm(sequence) {
  const progress = state.getProgress(sequence);
  if (!progress) return;
  
  const carrier = state.getCarrier(progress.tadig);
  const name = carrier ? carrier.name : progress.tadig;
  
  if (confirm(`案件 ${sequence} (${name}) を削除しますか?`)) {
    state.deleteProgress(sequence);
    renderProgressTable();
    renderOrderTable();
    renderDashboard();
  }
}
// ===================================
// Order Modal Functions
// ===================================
function closeOrderModal() {
  document.getElementById('orderModal').classList.add('hidden');
}
function editOrder(tadig) {
  const order = state.getOrder(tadig);
  if (!order) return;
  
  document.getElementById('orderEditId').value = tadig;
  document.getElementById('orderTadig').value = order.tadig;
  document.getElementById('orderCarrierName').value = order.carrierName;
  document.getElementById('orderDnsDate').value = order.dnsDate || '';
  document.getElementById('orderMmeDate').value = order.mmeDate || '';
  document.getElementById('orderTccDate').value = order.tccDate || '';
  document.getElementById('orderVerificationDate').value = order.verificationDate || '';
  document.getElementById('orderConfigLimit').value = order.configLimit || '';
  document.getElementById('orderPriority').value = order.priority;
  
  document.getElementById('orderModal').classList.remove('hidden');
}
function saveOrder() {
  const form = document.getElementById('orderForm');
  if (!form.checkValidity()) {
    form.reportValidity();
    return;
  }
  
  const tadig = document.getElementById('orderEditId').value;
  const order = {
    tadig: tadig,
    carrierName: document.getElementById('orderCarrierName').value,
    dnsDate: document.getElementById('orderDnsDate').value,
    mmeDate: document.getElementById('orderMmeDate').value,
    tccDate: document.getElementById('orderTccDate').value,
    verificationDate: document.getElementById('orderVerificationDate').value,
    configLimit: document.getElementById('orderConfigLimit').value.trim(),
    priority: document.getElementById('orderPriority').value
  };
  
  state.updateOrder(tadig, order);
  
  closeOrderModal();
  renderOrderTable();
  renderDashboard();
}
// ===================================
// Event Listeners
// ===================================
document.addEventListener('DOMContentLoaded', () => {
  // Navigation
  document.querySelectorAll('.sidebar-nav-link').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const view = link.getAttribute('data-view');
      switchView(view);
    });
  });
  
  // Master view
  document.getElementById('addMasterBtn').addEventListener('click', openMasterModal);
  document.getElementById('masterSearch').addEventListener('input', (e) => {
    renderMasterTable(e.target.value);
  });
  
  // Progress view
  document.getElementById('addProgressBtn').addEventListener('click', openProgressModal);
  document.getElementById('progressSearch').addEventListener('input', (e) => {
    renderProgressTable(e.target.value);
  });
  
  // Order view
  document.getElementById('orderSearch').addEventListener('input', (e) => {
    renderOrderTable(e.target.value);
  });
  
  // Modal close on overlay click
  document.querySelectorAll('.modal-overlay').forEach(overlay => {
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) {
        overlay.classList.add('hidden');
      }
    });
  });
  
  // Initialize with dashboard
  switchView('dashboard');
});
